2020-08-09 14:16:03,959 INFO 158477: Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/core/generic.py:2490: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['ensemble', 'structure', 'chain', 'hetero', 'insertion_code', 'segid',
       'resname', 'altloc', 'element', 'name', 'fullname', 'serial_number'],
      dtype='object')]

  pytables.to_hdf(
1713781
Traceback (most recent call last):
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 655, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1700, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 411, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file '/oak/stanford/groups/rondror/projects/combind/flexibility/atom3d/sharded/structures_meta_500.h5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "shard.py", line 302, in <module>
    shard_dataset()
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "shard.py", line 59, in shard_dataset
    Sharded.shard_one(ensemble_map, sharded_path, start, stop, shard_num)
  File "shard.py", line 110, in shard_one
    sharded._write_shard(shard_num, df)
  File "shard.py", line 273, in _write_shard
    metadata = pd.concat((pd.read_hdf(metadata_path, f'metadata'),
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 537, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 687, in open
    raise IOError(str(err))
OSError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1700, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 411, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file '/oak/stanford/groups/rondror/projects/combind/flexibility/atom3d/sharded/structures_meta_500.h5'
